# Changes here will be overwritten by Copier
_commit: 653f98b
_src_path: pypackage-template-fork
add_me_as_contributor: true
copyright_year: '2023'
documentation: true
email: 34j.95a2p@simplelogin.com
full_name: 34j
github_username: 34j
initial_commit: true
open_source_license: CC0 1.0 Universal
package_name: jinja2_env
project_name: jinja2-env
project_short_description: Jinja2 Extension for getting environment variables
project_slug: jinja2-env
run_poetry_install: false
setup_github: true
setup_pre_commit: false

